[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "jbackup"
authors = [
	{ name = "John Russell", email = "johndevlopment7@gmail.com" }
]
description = "Extensible backup system"
readme = "README.md"
dependencies = [
	     "tomli ; python_version < '3.11'",
	     "tomli-w"
]
requires-python = ">=3.10"
classifiers = [
	    "Programming Language :: Python :: 3",
	    "Programming Language :: Python :: 3.10",
	    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
	    "Operating System :: OS Independent"
]
dynamic = ["version"]

[project.urls]
"Homepage" = "https://github.com/JohnDevlopment/jbackup"
"Bug Tracker" = "https://github.com/JohnDevlopment/jbackup/issues"

[project.scripts]
jbackup = "jbackup.__main__:run"

[tools.setuptools.packages.find]
where = ["src"]

[tool.setuptools.dynamic]
version = {attr = "jbackup.__version__"}
